image: drsar/anaconda3

test_app:
  type: test
  script:
  - git submodule update --init --recursive 
  - py.test

pages:
  script:
  - cd doc
  - sphinx-build -b html -d _build/doctrees . _build/html
  - rm -rf ../.public ../public
  - mkdir ../.public
  - cp -r _build/html/* ../.public
  - mv ../.public ../public
  artifacts:
    paths:
    - public

